language: go
os:
  - linux
#  - osx
go:
- '1.13.x'
services:
- docker

sudo: required

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

install: true

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: "Testing QUIC"
      name: "Test QUIC"
      script:
        - go test -v -run TestClustersVersion -failfast -count 30 -consensus raft
    - name: "Test QUIC2"
      script:
        - go test -v -run TestClustersVersion -failfast -count 30 -consensus raft
    - name: "Test QUIC3"
      script:
        - go test -v -run TestClustersVersion -failfast -count 30 -consensus raft
    - name: "Test QUIC4"
      script:
        - go test -v -run TestClustersVersion -failfast -count 30 -consensus raft
